services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=skripsi_java_auto_grader'
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
