version: "3.8"

services:
  backend:
    image: java-auto-grader-backend:latest
    restart: unless-stopped
    env_file:
      - env.properties
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./logs:/app/logs
