version: '3.8'
services:
  gradle-sandbox:
    image: gradle:jdk21-alpine  # Use official Gradle image or your custom one
    container_name: gradle-sandbox
    volumes:
      - gradle-cache:/home/gradle/.gradle
      - gradle-wrapper-cache:/home/gradle/.gradle/wrapper
      - gradle-build-cache:/gradle-build-cache
      - ./workspace:/workspace
    working_dir: /workspace
    command: tail -f /dev/null  # Keep container running
    environment:
      - GRADLE_OPTS=-Xmx1g -XX:+UseG1GC -Dorg.gradle.daemon=true
      - GRADLE_USER_HOME=/home/gradle/.gradle
      - GRADLE_BUILD_CACHE_DIR=/gradle-build-cache
      - GRADLE_PARALLEL=true
      - GRADLE_CONFIGURE_ON_DEMAND=true
      - GRADLE_CACHING=true
    deploy:
      resources:
        limits:
          memory: 4g     # Increased for concurrent executions
          cpus: '4.0'    # Increased for better parallelism
        reservations:
          memory: 2g
          cpus: '2.0'
    tmpfs:
      - /tmp:size=1g,exec  # Fast temporary storage for build processes
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pgrep", "-f", "gradle" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  gradle-cache:
    driver: local
  gradle-wrapper-cache:
    driver: local
  gradle-build-cache:
    driver: local
